name: Integration
on:
  push:
    branches:
      - main
  pull_request: ~
  schedule:
    - cron: '0 7 * * 1'
jobs:
  stylua:
    name: Check codestyle
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: JohnnyMorganz/stylua-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          args: --color always --check .
